### ISSUE TITLE
Deploy OVRLipSync for Android

### ISSUE THREAD

**Issue by goatchurchprime** [goatchurchprime/two-voip-godot-4#10]
The windows one works because it's just a DLL that it can find.  There is equivalently an .so file for the Android version (none for linux, though) that it should be possible to deploy with the GDExtension .so file if you know what you are doing (either dynamically linked or static, if that can be done).  The OVRLipSync library appears to be completely self-contained without any outside dependencies beyond glibc.

**Comment by DmitriySalnikov** [comment]
Ok. Everything is broken because there are merge conflicts.

by the way, the file `addons/twovoip/twovoip.gdextension` is better not to delete

**Comment by goatchurchprime** [comment]
This is pretty amazing it works!  But I had to make the `twovoip_lipsync` library work for linux by copying across `libtwovoip.linux.template_debug.x86_64.so` from `twovoip` and editing the .gdextension file to find it.  Then deploying to Android automatically picked up the working lipsync plugin so that the version running on my phone had this feature!  

I don't know the best way to organize the system so that you still get versions without the lipsync library (where it runs my stub functions and returns -1) for compatibility. (My limited git knowledge has been stretched when merging these branches after my edits.  Hope there's no mistakes.)

The example can now function without the addon working by testing `ClassDB.can_instantiate("AudioEffectOpusChunked")`, which means it is more useful as a development tool.

This is going to make for some funny tests.  I managed to get the **LA** viseme to register.  This is the one corresponding to Laughter.
![image](https://github.com/user-attachments/assets/a9c0bb34-10b6-42a6-a382-0f242cc1d756)

**Comment by goatchurchprime** [comment]
This is a working project under android that uses it.  If I get it reliable then I can close this issue
 https://github.com/goatchurchprime/lipsync/?tab=readme-ov-file#lipsync

**Comment by goatchurchprime** [comment]
This is now terminally broken even on Windows, crashes immediately.  
I hope to compile and run it using pure scons to debug this.

**Comment by goatchurchprime** [comment]
Works now.  I have made a fake linux version to make deployment to android more easy.
