### ISSUE TITLE
Specify dependence Android NDK r23c now that r25 has disappeared from the github runners

### ISSUE THREAD

**Issue by goatchurchprime** [goatchurchprime/two-voip-godot-4#23]
It disappeared from the github runners shortly after the date mentioned here.
   https://github.com/actions/runner-images/issues/10342
   
Watch for if @DmitriySalnikov's [runners break](https://github.com/DmitriySalnikov/godot_debug_draw_3d/actions) too around now as it references NDK r23c, which is the version advised by https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_for_android.html#doc-compiling-for-android:

**Comment by DmitriySalnikov** [comment]
Even without this change, github runners have not contained NDK 23 for some time 🤷‍♂️
Therefore, my workflow installs NDK 23 before build.

**Comment by goatchurchprime** [comment]
You're absolutely correct. Somehow there is a missing CMake setting that is required to point to it, so it must have been working okay with some sort of hidden default of ndk25 until it disappeared.  I'm going to need help.

 ```scons: done reading SConscript files.
  scons: Building targets ...
  build_rnnoise(["build_rnnoise"], [])
  
  cmake config output: -- Configuring incomplete, errors occurred!
  
  cmake config errors: CMake Error at /usr/local/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:152 (message):
    Could not find toolchain file:
    /usr/local/lib/android/sdk/ndk/25.2.9519653/build/cmake/android.toolchain.cmake
  Call Stack (most recent call first):
    CMakeLists.txt:2 (project)
  
  
  CMake Error: CMake was unable to find a build program corresponding to "Ninja Multi-Config".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
  CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
 ```

**Comment by DmitriySalnikov** [comment]
Again the submodules are added as SSH and not HTTPS:
```
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:werman/noise-suppression-for-voice.git' into submodule path 'C:/My/Repositories/two-voip-godot-4/noise-suppression-for-voice' failed
Failed to clone 'noise-suppression-for-voice' a second time, aborting
failed to run git: exit status 1
```

Anyway #24

**Comment by goatchurchprime** [comment]
Works perfectly.  New asset uploaded
