### ISSUE TITLE
Disable built in proximity chat?

### ISSUE THREAD

**Issue by shortcakecafe** [goatchurchprime/two-voip-godot-4#35]
Hi, this library has been super useful to me lately!
I was wondering if there was a way to disable the built in proximity chat?
Or at least I think there's built in proximity set up?
I very much apologize if there isn't and it's some oversight in my own code.

**Comment by shortcakecafe** [comment]
Oops, completely my fault, I did not realize that a microphone on audiostreamplayer2d was also proximity based!

**Comment by shortcakecafe** [comment]
Essentially from what I gathered, if you put a microphone on an AudioStreamPlayer2D, then the further away you go, then the less it records your microphone, kinda like how it would work if you had audio coming out of it. If the AudioStreamPlayer is on your character, this isnt a problem since you're always close to it but mine was set on a stationary node for VOIP stuff.

**Comment by goatchurchprime** [comment]
I was stuck on the phrase: "the further away you go..." _**from what**_?

But the answer is in the docs: https://docs.godotengine.org/en/stable/classes/class_audiolistener2d.html

> If there is no active AudioListener2D in the current Viewport, center of the screen will be used as a hearing point for the audio. AudioListener2D needs to be inside SceneTree to function.
