### ISSUE TITLE
In Minimum Use Case, opuschunked does not have opus_chunk methnod,

### ISSUE THREAD

**Issue by Anotic** [goatchurchprime/two-voip-godot-4#38]
I was following the Minimum Use Case doc,
and when getting to the part about transmitting:

Now you can consume and transmit the byte chunks with the following code:

```
func _process(delta):
    var prepend = PackedByteArray()
    while opuschunked.chunk_available():
        var opusdata : PackedByteArray = opuschunked.opus_chunk(prepend)
        opuschunked.drop_chunk()
        transmit(opusdata)
```

Although "opuschunked" is an AudioEffectOpusChunked, it has no method "opus_chunk()" so it just crashes there.

![image](https://github.com/user-attachments/assets/dd0fee8d-0a31-48fd-8a2a-06e7cb9a6475)

**Comment by Anotic** [comment]
Forgot to mention I am on Godot 4.3 Stable and downloaded the plugin from the Asset Library

**Comment by goatchurchprime** [comment]
Sorry for the error.  Docs not keeping up with development.

To make it easier I've hurriedly included the minimal use case now, which you can run using Run Current Scene.  It's now got an audio message which you can play.

I should probably inline several of the other functions like the denoiser and resamplers (commented out) in the minimal to help with the next steps after the minimal.

**Comment by Anotic** [comment]
Thank you for replying! It all works now, I did have a look at some other functions to see if it had been renamed but I wasn't sure.
