### ISSUE TITLE
I'm about a request to configure GitHub Actions support

### ISSUE THREAD

**Issue by DmitriySalnikov** [goatchurchprime/two-voip-godot-4#4]
Where you asked the question, I can't answer, so I'm writing here.

What exactly are you interested in? I can set up scripts in a similar way to mine so that you have the Debug and Release libraries of libopus and yours on each commit.

Do you need LipSync library support in GH Action? And how do I download precompiled libraries? (try to download from the official website or copy them to the repository)

**Comment by ajlennon** [comment]
I've been helping @goatchurchprime @DmitriySalnikov and have added in GitHub actions which is based on your work.

Really impressive stuff - thanks for this it helped enormously

**Comment by DmitriySalnikov** [comment]
Yes, I saw it. I want to make a few edits now.

**Comment by DmitriySalnikov** [comment]
Finally I'm done https://github.com/goatchurchprime/two-voip-godot-4/pull/6

@ajlennon I do not know how you communicated with each other, but perhaps you can notify the author faster than notifications from GitHub. 😉

**Comment by goatchurchprime** [comment]
I'm sorry I had not found this conversation space till now.  I am trying to catch up.  

The ovrlipsync is a complicated story.  My stuff here is very experimental. From what I can tell, every VR app depends on it and there is no replacement.  It is only available as a binary on some platforms and is supposed to be end of life.  Getting it to deploy on Android would be legendary as this is what the standalone headsets use (though I do not know if deployments of extra libraries onto Android are possible).  The cool kids are bypassing it by using face tracking, but it is still interesting if you don't have that.  Face tracking might not be as crazy as it seems.  [Overte](https://overte.org/index.html) does face tracking straight from your a laptop's webcam using mediapipe.

**Comment by DmitriySalnikov** [comment]
@goatchurchprime So I can add generation of a separate archive with lipsync support (do I need to copy all libraries into it or only those that support lipsync? 🤔)
